version: '3'

services:
    rt0:
        image: pierky/gobgp
        volumes:
            - ./rt0:/etc/gobgp
        networks:
            bgpnetwork:
                ipv4_address: 172.18.0.2
    rt1:
        image: pierky/gobgp
        volumes:
            - ./rt1:/etc/gobgp
        networks:
            bgpnetwork:
                ipv4_address: 172.18.0.3

networks:
    bgpnetwork:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/24
